insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0001', 'Rosa vermelha', 5, 50, 'Rosas Chinensis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0002', 'Rosa amarela', 5, 50, 'Rosas Chinensis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0003', 'Rosa branca', 5, 50, 'Rosas Chinensis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0004', 'Rosa cor-de-rosa', 5, 50, 'Rosas Chinensis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0005', 'Orquídea branca', 50, 5, 'Orquídea Phalaenopsis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0006', 'Orquídea azul', 50, 5, 'Orquídea Phalaenopsis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0007', 'Orquídea amarela', 50, 5, 'Orquídea Phalaenopsis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0008', 'Orquídea cor-de-rosa', 50, 5, 'Orquídea Phalaenopsis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0009', 'Margarida branca', 5, 50, 'Margaridas');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0010', 'Margarida cor-de-rosa', 5, 50, 'Margaridas');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0011', 'Margarida amarela', 5, 50, 'Margaridas');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0012', 'Girassol Tradicional', 10, 50, 'Girassóis');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0013', 'Hortência Adria', 35, 25, 'Hortências');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0014', 'Hortência cor-de-rosa', 35, 25, 'Hortências');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0015', 'Peônias brancas', 30, 10, 'Peônia');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0016', 'Peônias cor-de-rosa', 30, 10, 'Peônia');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0017', 'Peônias amarelas', 30, 10, 'Peônia');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0018', 'Peônias azuis', 30, 10, 'Peônia');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0019', 'Rosa do Deserto vermelha', 50, 5, 'Rosa do Deserto');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0020', 'Rosa do Deserto amarela', 50, 5, 'Rosa do Deserto');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0021', 'Rosa do Deserto branca', 50, 5, 'Rosa do Deserto');
insert into produto (codigo, nome, valor, quantidade, categoria) values ('FLO0022', 'Violeta', 30, 25, 'Violetas');
